# Generated by Django 2.2.3 on 2019-07-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
    ]
