# Generated by Django 2.2.3 on 2019-07-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0007_auto_20190720_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='juegos',
        ),
        migrations.AddField(
            model_name='puntaje',
            name='juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaming.Juego'),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaming.Jugador'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fechaCreacion',
            field=models.DateField(verbose_name='fecha Creacion'),
        ),
    ]
