# Generated by Django 2.2.3 on 2019-07-21 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0010_auto_20190721_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha Creacion'),
        ),
    ]
