# Generated by Django 2.2.3 on 2019-07-02 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50, verbose_name='password')),
                ('fechaNacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listadoJuegos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(max_length=10)),
                ('fecha', models.DateTimeField(verbose_name='fecha puntaje')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Plataforma'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tiposRecomendados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Recomendado'),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('creador', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateTimeField(verbose_name='fecha Creacion')),
                ('puntaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Puntaje')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Tipo')),
            ],
        ),
    ]
