# Generated by Django 2.2.3 on 2019-07-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='jugador',
            name='juego',
            field=models.ManyToManyField(to='gaming.Juego'),
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='tiposRecomendados',
        ),
        migrations.AddField(
            model_name='jugador',
            name='tiposRecomendados',
            field=models.ManyToManyField(to='gaming.Recomendado'),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
    ]
