# Generated by Django 2.2.3 on 2019-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_auto_20190720_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fechaNacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha nacimiento'),
        ),
    ]
