# Generated by Django 2.2.3 on 2019-07-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0004_auto_20190720_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_nacimiento',
        ),
    ]
