# Generated by Django 2.2.3 on 2019-07-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0005_remove_jugador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='puntaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gaming.Puntaje'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gaming.Tipo'),
        ),
    ]
