# Generated by Django 2.2.3 on 2019-07-21 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0008_auto_20190720_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fechaCreacion',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 6, 11, 12, 571563), verbose_name='fecha Creacion'),
        ),
    ]
