# Generated by Django 2.2.3 on 2019-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0012_auto_20190721_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
